version: "3.3"

services:
  db:
    image: mysql:8
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3307:3306"
    volumes:
      - ocrdb:/var/lib/mysql
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  auth:
    build:
      context: ./auth_service
    command: ["./start_server.sh"]
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ".env"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}

volumes:
  ocrdb:
